INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO facilities(name) VALUES('vidéoprojecteur');
INSERT INTO facilities(name) VALUES('écran tactile');
INSERT INTO facilities(name) VALUES('microphone');
INSERT INTO facilities(name) VALUES('controlleur tactile');
INSERT INTO facilities(name) VALUES('sans équipements');
INSERT INTO rooms(capacity, name) VALUES ('30', 'Stade de France');
INSERT INTO rooms(capacity, name) VALUES ('15', 'rafale');
INSERT INTO rooms(capacity, name) VALUES ('20', '2L');
INSERT INTO rooms(capacity, name) VALUES ('50', 'Arena');
INSERT INTO room_facility(room_id, facility_id) VALUES (1,1);
INSERT INTO room_facility(room_id, facility_id) VALUES (1,2);
INSERT INTO room_facility(room_id, facility_id) VALUES (2,1);
INSERT INTO room_facility(room_id, facility_id) VALUES (3,3);
INSERT INTO room_facility(room_id, facility_id) VALUES (3,4);
INSERT INTO room_facility(room_id, facility_id) VALUES (4,5);
INSERT INTO users(birth_date, email, password, username) VALUES ('12/02/1992','leon.pofire@epfedu.fr','$2a$10$.bTat0HcXEUnDmvONRZ2LeluEO558I4EK/o.kK6bvnsEGmY.aas4e','leopof');
INSERT INTO user_roles(user_id, role_id) VALUES (1,2);
INSERT INTO user_roles(user_id, role_id) VALUES (1,1);
INSERT INTO users(birth_date, email, password, username) VALUES ('25/05/1992','marc.ofes@epfedu.fr','$2a$10$U5A6ACswlGZwdZBwAXOmSuv1LUF3Vq/5dNeAWXnrdJ3fMU3OP5l9a','marc ofes');
INSERT INTO user_roles(user_id, role_id) VALUES (2,1);
INSERT INTO reservations(begin_hour, date, end_hour, room_id, user_id) VALUES (1535,'2020-11-11 01:00:00.000000',1630,1,2);
INSERT INTO reservations(begin_hour, date, end_hour, room_id, user_id) VALUES (1545,'2020-11-12 01:00:00.000000',1645,2,1);
INSERT INTO reservations(begin_hour, date, end_hour, room_id, user_id) VALUES (1430,'2020-11-13 01:00:00.000000',1530,4,2);
INSERT INTO user_guest(user_id, reservation_id) VALUES (1,1);
INSERT INTO user_guest(user_id, reservation_id) VALUES (1,3);
