INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO facilities(name) VALUES('vidéoprojecteur');
INSERT INTO facilities(name) VALUES('écran tactile');
INSERT INTO facilities(name) VALUES('microphone');
INSERT INTO facilities(name) VALUES('controlleur tactile');
INSERT INTO facilities(name) VALUES('sans équipements');
INSERT INTO rooms(capacity, name) VALUES ('30', 'Stade de France');
INSERT INTO rooms(capacity, name) VALUES ('15', 'rafale');
INSERT INTO rooms(capacity, name) VALUES ('20', '2L');
INSERT INTO rooms(capacity, name) VALUES ('50', 'Arena');
